# Generated by Django 5.1.4 on 2024-12-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('character', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collaboration.document')),
            ],
        ),
    ]
