# Generated by Django 5.1.4 on 2024-12-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('upto_operation_id', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collaboration.document')),
            ],
        ),
    ]
